site_name: 基于摄影测量的三维重建
site_url: https://openhutb.github.io/3d/
repo_url: https://github.com/OpenHUTB/3d
edit_uri: edit/master/docs/

theme:
  name: readthedocs
  sticky_navigation: True
  navigation_depth: 3
  features:
    - search.suggest

extra_css:
  - extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://cdn.rawgit.com/knsv/mermaid/6.0.0/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js
  - js/umlconvert.js

plugins:
  - search:
      lang: ja
      separator: '[\s\-\.]+'
      min_search_length: 3

markdown_extensions:
  - admonition
  - mdx_math
  - pymdownx.superfences:
      custom_fences:
        - { name: flow, class: uml-flowchart }
        - { name: sequence, class: uml-sequence-diagram }
        - { name: mermaid, class: mermaid }

extra:
  generator: false

copyright: OpenHUTB 版权所有 &copy; 2025

nav:
  - 首页: index.md
  - 重建精度优化: einstein_method.md
